## This config.yml is an example, modify only config.yml.ref - which is used as reference. 
configs:
# config for specific id
## application web
- id: config-id #need to be unique
  config:
    name:
      name: HostGroupName
      type: environment
    template: application-web.json
    skip: false
  type:
    api: application-web
## application detection rule for domain easytravelxx-www (loadgen) and attached to the application web
- id: config-id
  config:
    name:
      format: "{{ .hostgroup }}-www"
      type: compound
      references:
        - hostgroup
      hostgroup:
        type: environment
        name: HostGroupName
    parameters:
      hostgroup:
        type: environment
        name: HostGroupName
      applicationId:
        configId: config-id
        configType: application-web
        property: id
        type: reference
    template: application-detection-rule-loadgen.json
    skip: false
  type:
    settings:
      schema: builtin:rum.web.app-detection
      scope: environment
## application detection rule for domain azure (real activity) and attached to the application web
## disable for admin training
- id: config-id-2
  config:
    name:
      name: HostGroupName
      type: environment
    parameters:
      applicationId:
        configId: config-id
        configType: application-web
        property: id
        type: reference
      domain:
        name: DomainName
        type: environment
    template: application-detection-rule-azure.json
    skip: true
  type:
    settings:
      schema: builtin:rum.web.app-detection
      scope: environment
## alerting profile based on management zone
- id: config-id
  config:
    name:
      name: HostGroupName
      type: environment
    parameters:
      mzid:
        configId: config-id
        configType: builtin:management-zones
        property: id
        type: reference
    template: alerting-profile.json
    skip: false
  type:
    settings:
      schema: builtin:alerting.profile
      scope: environment
## management zone (used by alerting profile, dashboard and maintenance window) 
- id: config-id
  config:
    name:
      name: HostGroupName
      type: environment
    template: management-zone.json
    skip: false
  type:
    settings:
      schema: builtin:management-zones
      scope: environment
## problem notification based on alerting profile and need "Email" parameter 
- id: config-id
  config:
    name:
      name: HostGroupName
      type: environment
    parameters:
      alertingprofileId:
        configId: config-id
        configType: builtin:alerting.profile
        property: id
        type: reference
      email:
        name: Email
        type: environment
    template: notification.json
    skip: false
  type:
    settings:
      schema: builtin:problem.notifications
      scope: environment
## http monitor
## disable for admin training
- id: config-id
  config:
    name:
        type: environment
        name: HostGroupName
    parameters:
      hostgroup:
        type: environment
        name: HostGroupName
      applicationId:
        configId: config-id
        configType: application-web
        property: id
        type: reference
      domain:
        name: DomainName
        type: environment
      site1:     
        name: PublicSyntheticLocation1
        type: environment
      site2:
        name: PublicSyntheticLocation2
        type: environment
    template: synthetic-http-monitor.json
    skip: true
  type:
    api: synthetic-monitor
## browser monitor
## disable for admin training
- id: config-id-2
  config:
    name: 
      format: "{{ .hostgroup }} - click path"
      type: compound
      references:
        - hostgroup
      hostgroup:
        type: environment
        name: HostGroupName
    parameters:
      hostgroup:
        type: environment
        name: HostGroupName
      applicationId:
        configId: config-id
        configType: application-web
        property: id
        type: reference
      domain:
        name: DomainName
        type: environment
      site1:
        name: PublicSyntheticLocation1
        type: environment
      site2:
        name: PublicSyntheticLocation2
        type: environment
    template: synthetic-browser-monitor.json
    skip: true
  type:
    api: synthetic-monitor
## maintenance window based on management zone (disable notification on not business hours) 
- id: config-id
  config:
    name:
      name: HostGroupName    
      type: environment
    parameters:
      mzid:
        configId: config-id
        configType: builtin:management-zones
        property: id
        type: reference
    template: maintenance-window.json
    skip: false
  type:
    settings:
      schema: builtin:alerting.maintenance-window
      scope: environment
## special dashboard based on management zone and associated to Email user 
- id: config-id
  config:
    name:
      name: HostGroupName
      type: environment
    parameters:
      hostgroup:
        name: HostGroupName
        type: environment
      domain:
        name: DomainName
        type: environment
      mzid:
        configId: config-id
        configType: builtin:management-zones
        property: id
        type: reference
      owner:
        name: Email
        type: environment
    template: dashboard.json
    skip: false
  type:
    api: dashboard
# generic config
## auto tag "app" use regex _(.++)
- id: tag-env
  config:
    name: env
    template: auto-tag-env.json
    skip: false
  type:
    settings:
      schema: builtin:tags.auto-tagging
      scope: environment
## auto tag "env" use regex ([^_]++)
- id: tag-app
  config:
    name: app
    template: auto-tag-app.json
    skip: false
  type:
    settings:
      schema: builtin:tags.auto-tagging
      scope: environment
## auto tag "bu" use metadata bu
- id: tag-bu
  config:
    name: bu
    template: auto-tag-bu.json
    skip: false
  type:
    settings:
      schema: builtin:tags.auto-tagging
      scope: environment
## renaming host 
- id: host-naming
  config:
    name: host-naming
    template: conditional-naming-host.json
    skip: false
  type:
    api: conditional-naming-host
## renaming process group 
- id: processgroup-naming
  config:
    name: processgroup-naming
    template: conditional-naming-processgroup.json
    skip: false
  type:
    api: conditional-naming-processgroup
## renaming service 
- id: service-naming-nginx
  config:
    name: service-naming-nginx
    template: conditional-naming-service-nginx.json
    skip: false
  type:
    api: conditional-naming-service
- id: service-naming
  config:
    name: service-naming
    template: conditional-naming-service.json
    skip: false
  type:
    api: conditional-naming-service
